feat: Quickstart 3.0
flexpa/quickstart pull request #130
Opened 2024-11-05 03:17 UTC by jdjkelly

## Why
* We are preparing to launch a new Quickstart guide and part of that release involves a new version of the source repository

## What
* Moves the example into one single NextJS project instead of having two applications
* New functionality for the Quickstart with API usage examples directly in app

2024-11-06 22:16 UTC, larry-flexpa requested changes
Is this missing the env.example?

2024-11-07 15:32 UTC, larry-flexpa approved these changes
Only problem is the patient authorization link doesn't go anywhere, but otherwise looks great! Excited to use this.

2024-11-07 15:32 UTC, larry-flexpa commented on src/app/dashboard/page.tsx
> +          Congrats! By linking a health insurance plan, you have created a <a href="https://docs.flexpa.com/reference/patient-authorization" className="text-black font-semibold underline">Patient Aut
Our docs don't have a reference here. Also our docs are at `https://www.flexpa.com/docs`

2024-11-07 15:41 UTC, jdjkelly commented on src/app/dashboard/page.tsx
> +          Congrats! By linking a health insurance plan, you have created a <a href="https://docs.flexpa.com/reference/patient-authorization" className="text-black font-semibold underline">Patient Aut
Hallucination...

2024-11-07 19:18 UTC, jdjkelly commented on src/app/dashboard/page.tsx
> +          Congrats! By linking a health insurance plan, you have created a <a href="https://docs.flexpa.com/reference/patient-authorization" className="text-black font-semibold underline">Patient Aut
```suggestion
          Congrats! By linking a health insurance plan, you have created a Patient Authorization.
```

2024-11-07 19:19 UTC, merged